name: flutter_chat_shell
description: A Flutter chat app template with GoRouter, Firebase, and Supabase.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.1.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.0.16
  firebase_messaging: ^14.9.4
  supabase_flutter: ^2.10.0
  json_annotation: ^4.8.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.5.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
     - lib/assets/avatar_placeholder.png





